### ISSUE TITLE
AWS Zarf package should use remote state file

### ISSUE THREAD

**Issue by runyontr** [defenseunicorns/zarf-package-big-bang#139]
Using a local state file is not ideal for many reasons.  We need a way to be able to either provide a remote state s3 bucket to use for our Loki terraform, or bootstrap our own s3 bucket for the state.

**Acceptance Criteria:**
* [ ] Module should be able to be deployed from a `zarf package deploy` command.

**Comment by wirewc** [comment]
Picking up this issue now. I am speaking with @MxNxPx and @cmharden to see what is needed.

**Comment by UncleGedd** [comment]
Closing in favor of: https://github.com/defenseunicorns/zarf-package-big-bang/issues/200
