### ISSUE TITLE
Loki unable to push logs to S3

### ISSUE THREAD

**Issue by UncleGedd** [defenseunicorns/zarf-package-big-bang#217]
On a fresh install of DUBBD-AWS, the Loki pods come up healthy but the logs indicate errors in the write operation. Both `loki-write` pod logs show the following:

```
AccessDenied: Not authorized to perform sts:AssumeRoleWithWebIdentity
```

Noting too that the loki bucket in S3 is empty

**Comment by justin-o12** [comment]
PR https://github.com/defenseunicorns/uds-iac-aws-s3/pull/6
