### ISSUE TITLE
Enable Persistance in Monitoring

### ISSUE THREAD

**Issue by runyontr** [defenseunicorns/zarf-package-big-bang#22]
Prometheus should be configured with a PVC or S3 bucket or Database/etc to store data.

Not sure how that's supposed to be done right now. @mjnagel do you have any examples of this?

**Comment by mjnagel** [comment]
For PVC based storage I *think* it's pretty easy on prometheus: https://docs-bigbang.dso.mil/1.54.0/docs/understanding-bigbang/package-architecture/monitoring/#Prometheus-Operator

If you're looking at the potential for multi-replica Prometheus you'd also need to pull in Thanos, which is where S3 could be tied in: https://docs-bigbang.dso.mil/1.54.0/docs/understanding-bigbang/package-architecture/monitoring/#Prometheus_1

**Comment by runyontr** [comment]
Ahhh thank you @mjnagel , I think I was worried about the HA portion Prometheus.  Looks fairly straight forward for adding storage.  Thanks!
