### ISSUE TITLE
Upgrade process

### ISSUE THREAD

**Issue by MxNxPx** [defenseunicorns/zarf-package-big-bang#26]
What does an "upgrade" an existing deployment look like:
* go to new release of BB
* add or delete a BB component to an existing deployment (same BB release)
* support - does it support and upgrade that skips versions (going from 1.52.0 to 1.54.0)

**Comment by runyontr** [comment]
In my head, the components within this distro are pretty locked in, but maybe that shouldn't be the case... I could see wanting to support some optional Zarf components (e.g. cert-manager, external-dns) that might not be needed for every environment.  Should we treat those as separate packages that a Platform admin can add to this package, or part of that package?


I think having them as separate packages make this package simplier, but it could complicate how we might need to share data between this package and those packages until https://github.com/defenseunicorns/pepr is ready to add

**Comment by cmharden** [comment]
We need to consider the versions allowed to be skipped when upgrading.  
E.g., upgrades between 0.1.x -> 0.2.x or 0.2.x -> 0.3.x are allowed, however 0.1.x -> 0.3.x isn't allowed.

**Comment by gregclark-defenseunicorns** [comment]
@cmharden I have a list of people I am reaching out to on delivery (Project Blue, CMS, HNCD, ValidEval, CNET/DI2ME, 45th) to ask them about their deployment process/experience. I would think we could uncover upgrade pain points from this. Or are you wanting to find someone else?

**Comment by UncleGedd** [comment]
Closing in favor of: https://github.com/defenseunicorns/zarf-package-big-bang/issues/14
