### ISSUE TITLE
Add linux_amd64 binary for Terraform to AWS Package

### ISSUE THREAD

**Issue by runyontr** [defenseunicorns/zarf-package-big-bang#75]
When running the AWS package, we currently only provide the darwin_arm64 binary for terraform and the terraform aws provider.

We need to be able to include both this architecture and the linux_amd64 and darwin_amd64 versions.  The use of which binary/provider should be conditioned on the environment of where the binary is being run, NOT the architecture of the package, which needs to be amd64 to support IronBank images

The IaC Example does this with a Makefile: https://github.com/defenseunicorns/iac/blob/main/examples/zarf-complete-example/Makefile#L9-L34 and then passes that as a variable into the zarf package.  I would prefer it to be self-contained within the zarf package so no external tools are needed to help orchestrate.

**Comment by zachariahmiller** [comment]
@runyontr For the iac specific packages, cant that just be accomplished by input variables to the zarf package create? The call to download terraform in the zarf.yaml already templates the arch/proc https://github.com/defenseunicorns/iac/blob/main/examples/zarf-complete-example/zarf.yaml#L71

Like in the Makefile noted in the ticket, set the inputs like so ` zarf package create --set ARCH_NAME=$(ARCH_NAME) --set ARCH_PROC=$(ARCH_PROC)` then you can set darwin_arm64 or linux_amd64

Since big bang is not deployed in this package, it is just aws infrastructure, it is agnostic to the target platform's arch(amd64). 

Or are you asking for the zarf packages to support multi-arch inherently? If thats the case, then as the zarf packages are transitioning to being OCI registry based, wouldn't it make sense at that time to build a multi-arch packages similar to how a multi-arch containers are done today, with their respective arch images and manifest?

**Comment by runyontr** [comment]
I think that could be possible.   When this is hosted on an OCI registry, that would require a completely different package for deploying this on a linux vs darwin machine, which isn't ideal in my mind.

In my head, the ability for one package to be able to work on anyone's machine is the value there and not having to worry about which architecture is being used by the client, which may or may not be the same architecture that the package was created on.

**Comment by runyontr** [comment]
> wouldn't it make sense at that time to build a multi-arch packages similar to how a multi-arch containers are done today, with their respective arch images and manifest?

This is kinda the issue.  I'd like this package to be multi-arch, and the way to do that requires us to figure out how to pull down all the arch's we want and then toggle between them based on the environment that the package is being deployed from.

**Comment by wirewc** [comment]
@runyontr for the multi-arch package, we have 2 options.
1.) Pack every binary type into a single package (essentially doubling or tripling the size based on the architectures)
2.) Get the Makefile to build one of each package for each architecture target. 

The intended use of the Makefile in the IaC repo right now is for the deployment engineering to perform a git clone on the repo, and build the the zarf package on the same system. The Makefile from the example was never intended to be for distribution of package to other systems. 

We can replicate the behavior mentioned in option number 1 referenced above, but it will significantly complicate the deployment package + make the packages multiples larger. 

What I think is the best solution is option 2 which is 1 Zarf package per architecture (which is how containers work after additional manifest functionality). 

Finally, the Makefile in the IaC repo fails when I try to run it locally. This Makefile has been ignored for some time and not presently working.

**Comment by runyontr** [comment]
I like breaking it down cleanly into those two options, and agree they both have their pros/cons.

I think we'll find the size of the binary is trivial compared to the images that are being injected, and while the complexity of the zarf package is there for our package developers, the simplicity for end users not having to figure out which package to use seems worth it.

And copy on the Makefile not working, just thinking that something external orchestrating the creation/use of the zarf.yaml seems like an extra layer of complexity I'd rather not have users deal with.  Docker has the perfect compliment to the different architectures that ensures the right architecture is pulled down when `docker pull` is called.  Zarf hasn't done that yet, so there's some additional steps to identify and pull down the correct package.

**Comment by wirewc** [comment]
So taking what @zachariahmiller was mentioning, I THINK what is needed for the best of both/all worlds is a solution that will: 
1. Have some sort of metadata file with one variables for `architecture`, `processor_family` (ARM only for now), and `operating_system`. 
1. manifest/digest system similar to container registries (e.g. OCI) 
1. Client can then call a manifest, compare and match the manifest with the keys from first item, and pull the package as needed. 
   1. Ideally, all packages will build per architecture needs. 
   
In the mean time, I have created a private repo to try and fix the Makefile for now with a very simple, straight forward example for reference and feedback before touching the [iac](https://github.com/defenseunicorns/iac) repo. I hope we can address and easily implement making a package per desired processor/os target with the Makefile to get you up and running soon and address the original issue for the moment.
