### ISSUE TITLE
Renovate Bot to look for updates to BigBang

### ISSUE THREAD

**Issue by runyontr** [defenseunicorns/zarf-package-big-bang#8]
Should look to automate looking for BigBang updates

**Comment by MxNxPx** [comment]
perhaps we have it look for a regex similar to this approach?
https://github.com/MxNxPx/flux2-gitops-repo/blob/master/.github/renovate.json5#L36-L44

and of course have it PR when a newer release (major/minor) is available:
https://repo1.dso.mil/big-bang/bigbang/-/releases

**Comment by MxNxPx** [comment]
drafted how this could be done...
config: https://github.com/MxNxPx/zarf-package-big-bang/blob/main/renovate.json
resulting renovate PR: https://github.com/MxNxPx/zarf-package-big-bang/pull/2/files
@runyontr - what do you think?

i'm happy to PR you feel like it looks semi-decent.

**Comment by runyontr** [comment]
Can you update your repo so that the zarf-config.toml is switched to zarf-config.yaml?  I would like to see if your config picks up this change as well: https://github.com/MxNxPx/zarf-package-big-bang/blob/main/cocowow/zarf-config.toml#L5
